### PR TITLE
improve handling of destination directory

### PR DESCRIPTION
**Pull request by scoopex**
- interactive: ask user for creating a not existing dest dir
    - no-clobber: do not write to a non empty directory (overrides -interactive option)
    - create: option to create destination dir if it does not exist
    - update documentation

### CODE REVIEW

**Comment by hweidner** [comment]
>stop execution if destination dir is not empty

I don't get why is an avantage? Neither cp nor rsync do that. I think it is a valid use case to merge data from different source into one directory.

>stop execution if destination does not exist  
>option to create destination if it does not exist

These could be considered for including. psync should either stop in this case, or create the directory automatically. The first looks more naturally to me, however the latter is closer to what cp and rsync do. Anyway, if the latter is implemented, it has to follow the `-owner` and `-times` flags.

>use a dynamic number of default threads (number of cpus multiplied by 2)

This will not be accepted. The concurrency level of the psync is solely unrelated to the number of CPU cores, as copying files is not a CPU bound operation. The value is determined only by the latency and throughput of the network file system. Moreover, this change leads to situations where bugs and performance figures that are hard to reproduce on other systems.

**Comment by scoopex** [comment]
Thanks for the feedback :-)

> > stop execution if destination dir is not empty
> 
> I don't get why is an avantage? Neither cp nor rsync do that. I think it is a valid use case to merge data from different source into one directory.

I added this from the view of my typical usage scenario replicating filesystems to another media/type.
I just wanted to prevent accidental replication to a already populated directory which is most of the time not that i want to do.
Psync outputs also error messages which complain that directories already exists,
Do you prefer to drop that enhancement or do think it would be better to have a "-force" flag?

> > use a dynamic number of default threads (number of cpus multiplied by 2)
> 
> This will not be accepted. The concurrency level of the psync is solely unrelated to the number of CPU cores, as copying files is not a CPU bound operation. The value is determined only by the latency and throughput of the network file system. Moreover, this change leads to situations where bugs and performance figures that are hard to reproduce on other systems.

That's right - the number of cpus does not really correlate of the number of the suitable parallel copy operations for the involved devices or filesystems.
It is difficult to guess a good value because we cannot know what types of network filesystems or hardware devices are involved in the copy operation.
Using the number of CPUs multiplied by 2 is just a heuristic guess. 
If you want to prevent unexpected situation and to increase reproducibility it might be a good thing to set it to a lower value  of to make "-threads" option mandatory (but changing that breaks backwards compatibility).
No pain to drop that :-)

**Comment by scoopex** [comment]
Updated commit. 

- automatic sizing of threads removed
- added option to check for empty dest dir

**Comment by hweidner** [comment]
Thank you for your contribution.

> I added this from the view of my typical usage scenario replicating filesystems to another media/type.
> I just wanted to prevent accidental replication to a already populated directory which is most of the time not that i want to do.
> Psync outputs also error messages which complain that directories already exists,

I still consider this feature not UNIX-like. When run interactively, the time to type "-checkempty" could better be used to check the destination directory directly. In a batch/script, this check could be done right before the call of psync, when it is appropriate for the use case.

I would merge the other two changes (check or create destination directory) without this one.

> It is difficult to guess a good value because we cannot know what types of network filesystems or hardware devices are involved in the copy operation.
> Using the number of CPUs multiplied by 2 is just a heuristic guess.

I am not sure if 16 is the best choice. It is there because psync was originally written for GlusterFS. But it should be hard coded, independent of the execution environment.

**Comment by scoopex** [comment]
> I still consider this feature not UNIX-like. When run interactively, the time to type "-checkempty" could better be used to check the destination directory directly. In a batch/script, this check could be done right before the call of psync, when it is appropriate for the use case.

Thanks for the feedback. You are right - it  might by better from usability perspective to implement something compareable "-n" and "-i" of the linux "cp" command.
I updated the pull request title.

**Comment by hweidner** [comment]
I have committed a change to check or create the destination directory (as stated above). Your contribution is honored in the commit comment.

From an 'interactive' flag, I would expect that it works recursively, like in Unix 'cp -ri'. However, I believe that interaction makes no sense while copying in parallel. An option like 'no-clobber' might be added when the sync mode is implemented, see GOALS.md. It will then also work recursively and also for files.

Maybe due to my lack of experience, I'm confused with too much changes on unrelated topics in one single pull request. It's better to discuss improvements in separate issues.

**Pull request closed without merging**
